version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5093:5092"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=fournisseur_identite;Username=postgres;Password=Etu002610

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Etu002610
      POSTGRES_DB: fournisseur_identite
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
